image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - review

build:
  stage: build
  tags:
    - runner-for-task-service
  script:
    - docker compose -f docker/docker-compose.yml down
    - docker compose -f docker/docker-compose.yml build


test:
  stage: test
  tags:
    - runner-for-task-service
  script:
    - docker compose -f docker/docker-compose.yml up -d db
    - docker compose -f docker/docker-compose.yml run --rm api pytest tests --cov
    - docker compose -f docker/docker-compose.yml stop db
  dependencies:
    - build

review:
  stage: review
  tags:
    - runner-for-task-service
  script:
    - docker compose -f docker/docker-compose.yml run --rm api pylint --verbose src
    - docker compose -f docker/docker-compose.yml down
