
services:
  api:
    build: ./
    container_name: api-task-service
    working_dir: /src
    command: >
      sh -c "uvicorn main:app --host ${HOST} --port ${HOST_PORT}"
    networks:
      - my-network
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    depends_on:
      - db
    env_file:
      - .env-non-dev


  db:
    image: postgres:14
    container_name: db-task-service
    networks:
      - my-network
    command: -p 5436
    ports:
      - "${DB_PORT}:5436"
    expose:
      - "${DB_PORT}"
    env_file:
      - .env-non-dev


networks:
  my-network:
    driver: bridge
    external: true
